services:
  adlumin-forwarder:
    image: ghcr.io/rumenblack84/adlumin-forwarder-docker:latest
    environment:
      - user=1000:1000 #Match to the UID & GID of the user you want to run the docker as. It's important they have permission to access the files where we have our bind mount located. This will also avoid running the container process itself as root which is good for security.
      - UMASK=022 # set umask 022 will cause all files to have 755 perms
      - TENANT_ID=
      - SOPHOS_API=
      - OFFICE365_TOKEN=
      - RUN_EDIT_SCRIPT=yes
      - S3_AKEY=
      - S3_SKEY=
    ports:
      # Network Security Devices
      - "514:514"
      - "514:514/udp"
      # Firewall
      - "20000:20000"
      - "20000:20000/udp"
      # VPN
      - "20001:20001"
      - "20001:20001/udp"
      # Misc1
      - "20002:20002"
      - "20002:20002/udp"
      # Misc2
      - "20003:20003"
      - "20003:20003/udp"
      # Carbon Black
      - "20005:20005"
      - "20005:20005/udp"
      # Carbon Black Defense
      - "20006:20006"
      - "20006:20006/udp"
      # Dark Trace
      - "20007:20007"
      - "20007:20007/udp"
      # Network Security Devices
      - "30000:30000"
      - "30000:30000/udp"
      # Endpoint Security
      - "30001:30001"
      - "30001:30001/udp"
      # misc3
      - "30002:30002"
      - "30002:30002/udp"
      # misc4
      - "30003:30003"
      - "30003:30003/udp"
      # misc5
      - "30005:30005"
      - "30005:30005/udp"
      # misc6
      - "30006:30006"
      - "30006:30006/udp"
      # misc7
      - "30007:30007"
      - "30007:30007/udp"
      # misc8
      - "30008:30008"
      - "30008:30008/udp"
      # misc9
      - "30009:30009"
      - "30009:30009/udp"
      # misc10
      - "30010:30010"
      - "30010:30010/udp"
      # Sophos
      - "31000:31000"
      - "31000:31000/udp"
      # Crowd Strike
      - "32000:32000"
      - "32000:32000/udp"
      # Hpux
      - "40001:40001"
      - "40001:40001/udp"
      # Aix
      - "40002:40002"
      - "40002:40002/udp"
      # Office365
      - "45000:45000"
      - "45000:45000/udp"
# Uncomment Section 1 of 2 to enable macvlan networking
# This will allow us to assign routable IP address from the hosts network to the container
# This can be very useful due to the amount of ports we are using so that we don't run out 
#    networks:
#      macvlan_net:
#        ipv4_address: 192.168.0.100 # Assign routable IP to container
    volumes:
      - /appdata/adlumin/forwarder:/usr/local/adlumin
# Uncomment Section 2 of 2 to enable macvlan networking 
# This will allow us to assign routable IP address from the hosts network to the container
# This can be very useful due to the amount of ports we are using so that we don't run out 
# networks:
#  macvlan_net:
#    driver: macvlan
#    driver_opts:
#      parent: eth0  # Replace with your host's network interface
#    ipam:
#      config:
#        - subnet: 192.168.0.0/24
#          gateway: 192.168.0.1  # Replace with your network's gateway
#          ip_range: 192.168.0.192/27  # Define a range for your containers