name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        env:
          GHCR_PAT: ${{ secrets.GHCR_PAT_adlumin_forwarder_docker }}
        run: echo "${{ secrets.GHCR_PAT_adlumin_forwarder_docker }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
     
      - name: Set lowercase repository owner
        id: repo-owner
        run: echo "::set-output name=owner-lowercase::$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')"

      - name: Build and push Docker image
        env:
          REPOSITORY_OWNER_LOWERCASE: ${{ steps.repo-owner.outputs.owner-lowercase }}
        run: |
          docker build -t ghcr.io/${REPOSITORY_OWNER_LOWERCASE}/adlumin-forwarder-docker:latest .
          docker push ghcr.io/${REPOSITORY_OWNER_LOWERCASE}/adlumin-forwarder-docker:latest
